default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  user: gearhead_base
  pool: 10
  timeout: 5000
  password: gearhead_base

development:
  <<: *default
  database: gearhead_development

test:
  <<: *default
  database: gearhead_test

sandbox:
  <<: *default
  host: localhost
  database: gearhead_sandbox

production:
  <<: *default
  host:  localhost
  database: gearhead_production