default: &default
  host: localhost #10.1.1.11
  adapter: postgresql
  encoding: unicode
  user: postgres
  pool: 10
  timeout: 5000
  password: p0stgr3s

development:
  <<: *default
  database: gearhead_development

test:
  <<: *default
  database: gearhead_test

sandbox:
  <<: *default
  host: localhost
  database: gearhead_sandbox

production:
  <<: *default
  host:  localhost
  database: gearhead_production