class LoadDataToModels < ActiveRecord::Migration[7.0]
  def change
    Model.find_or_create_by(brand_type: 25, name: "INTEGRA")
    Model.find_or_create_by(brand_type: 25, name: "LEGEND")
    Model.find_or_create_by(brand_type: 25, name: "NSX")
    Model.find_or_create_by(brand_type: 27, name: "MARRUA")
    Model.find_or_create_by(brand_type: 28, name: "145")
    Model.find_or_create_by(brand_type: 28, name: "147")
    Model.find_or_create_by(brand_type: 28, name: "155")
    Model.find_or_create_by(brand_type: 28, name: "156")
    Model.find_or_create_by(brand_type: 28, name: "164")
    Model.find_or_create_by(brand_type: 28, name: "166")
    Model.find_or_create_by(brand_type: 28, name: "2300")
    Model.find_or_create_by(brand_type: 28, name: "SPIDER")
    Model.find_or_create_by(brand_type: 156, name: "HUMMER")
    Model.find_or_create_by(brand_type: 16, name: "AM 825")
    Model.find_or_create_by(brand_type: 16, name: "HI TOPIC")
    Model.find_or_create_by(brand_type: 16, name: "ROCSTA")
    Model.find_or_create_by(brand_type: 16, name: "TOPIC")
    Model.find_or_create_by(brand_type: 16, name: "TOWNER")
    Model.find_or_create_by(brand_type: 32, name: "100")
    Model.find_or_create_by(brand_type: 32, name: "80")
    Model.find_or_create_by(brand_type: 32, name: "A1")
    Model.find_or_create_by(brand_type: 32, name: "A3")
    Model.find_or_create_by(brand_type: 32, name: "A4 SEDAN")
    Model.find_or_create_by(brand_type: 32, name: "A5 COUPE")
    Model.find_or_create_by(brand_type: 32, name: "A6 SEDAN")
    Model.find_or_create_by(brand_type: 32, name: "A7")
    Model.find_or_create_by(brand_type: 32, name: "A8")
    Model.find_or_create_by(brand_type: 32, name: "Q3")
    Model.find_or_create_by(brand_type: 32, name: "Q5")
    Model.find_or_create_by(brand_type: 32, name: "Q7")
    Model.find_or_create_by(brand_type: 32, name: "R8")
    Model.find_or_create_by(brand_type: 32, name: "RS3")
    Model.find_or_create_by(brand_type: 32, name: "RS4")
    Model.find_or_create_by(brand_type: 32, name: "RS5")
    Model.find_or_create_by(brand_type: 32, name: "RS6")
    Model.find_or_create_by(brand_type: 32, name: "S3")
    Model.find_or_create_by(brand_type: 32, name: "S4 SEDAN")
    Model.find_or_create_by(brand_type: 32, name: "S6 SEDAN")
    Model.find_or_create_by(brand_type: 32, name: "S8")
    Model.find_or_create_by(brand_type: 32, name: "TT")
    Model.find_or_create_by(brand_type: 32, name: "TTS")
    Model.find_or_create_by(brand_type: 157, name: "BUGGY")
    Model.find_or_create_by(brand_type: 155, name: "DEVILLE")
    Model.find_or_create_by(brand_type: 155, name: "ELDORADO")
    Model.find_or_create_by(brand_type: 155, name: "SEVILLE")
    Model.find_or_create_by(brand_type: 42, name: "JAVALI")
    Model.find_or_create_by(brand_type: 6, name: "MINI STAR FAMILY")
    Model.find_or_create_by(brand_type: 6, name: "MINI STAR UTILITY")
    Model.find_or_create_by(brand_type: 47, name: "CIELO")
    Model.find_or_create_by(brand_type: 47, name: "FACE")
    Model.find_or_create_by(brand_type: 47, name: "QQ")
    Model.find_or_create_by(brand_type: 47, name: "S 18")
    Model.find_or_create_by(brand_type: 47, name: "TIGGO")
    Model.find_or_create_by(brand_type: 19, name: "300C")
    Model.find_or_create_by(brand_type: 19, name: "CARAVAN")
    Model.find_or_create_by(brand_type: 19, name: "CIRRUS")
    Model.find_or_create_by(brand_type: 19, name: "GRAN CARAVAN")
    Model.find_or_create_by(brand_type: 19, name: "LE BARON")
    Model.find_or_create_by(brand_type: 19, name: "NEON")
    Model.find_or_create_by(brand_type: 19, name: "PT CRUISER")
    Model.find_or_create_by(brand_type: 19, name: "SEBRING")
    Model.find_or_create_by(brand_type: 19, name: "STRATUS")
    Model.find_or_create_by(brand_type: 19, name: "TOWN E COUNTRY")
    Model.find_or_create_by(brand_type: 19, name: "VISION")
    Model.find_or_create_by(brand_type: 5, name: "AIRCROSS")
    Model.find_or_create_by(brand_type: 5, name: "AX")
    Model.find_or_create_by(brand_type: 5, name: "BERLINGO")
    Model.find_or_create_by(brand_type: 5, name: "BX")
    Model.find_or_create_by(brand_type: 5, name: "C3")
    Model.find_or_create_by(brand_type: 5, name: "C4")
    Model.find_or_create_by(brand_type: 5, name: "C5")
    Model.find_or_create_by(brand_type: 5, name: "C6")
    Model.find_or_create_by(brand_type: 5, name: "C8")
    Model.find_or_create_by(brand_type: 5, name: "DS3")
    Model.find_or_create_by(brand_type: 5, name: "EVASION")
    Model.find_or_create_by(brand_type: 5, name: "JUMPER")
    Model.find_or_create_by(brand_type: 5, name: "XANTIA")
    Model.find_or_create_by(brand_type: 5, name: "XM")
    Model.find_or_create_by(brand_type: 5, name: "XSARA")
    Model.find_or_create_by(brand_type: 5, name: "ZX")
    Model.find_or_create_by(brand_type: 50, name: "CL 244")
    Model.find_or_create_by(brand_type: 50, name: "CL 330")
    Model.find_or_create_by(brand_type: 51, name: "ESPERO")
    Model.find_or_create_by(brand_type: 51, name: "LANOS")
    Model.find_or_create_by(brand_type: 51, name: "LEGANZA")
    Model.find_or_create_by(brand_type: 51, name: "NUBIRA")
    Model.find_or_create_by(brand_type: 51, name: "PRINCE")
    Model.find_or_create_by(brand_type: 51, name: "RACER")
    Model.find_or_create_by(brand_type: 51, name: "SUPER SALON")
    Model.find_or_create_by(brand_type: 51, name: "TICO")
    Model.find_or_create_by(brand_type: 52, name: "APPLAUSE")
    Model.find_or_create_by(brand_type: 52, name: "CHARADE")
    Model.find_or_create_by(brand_type: 52, name: "CUORE")
    Model.find_or_create_by(brand_type: 52, name: "FEROZA")
    Model.find_or_create_by(brand_type: 52, name: "GRAN MOVE")
    Model.find_or_create_by(brand_type: 52, name: "MOVE VAN")
    Model.find_or_create_by(brand_type: 52, name: "TERIOS")
    Model.find_or_create_by(brand_type: 18, name: "AVENGER")
    Model.find_or_create_by(brand_type: 18, name: "DAKOTA")
    Model.find_or_create_by(brand_type: 18, name: "JOURNEY")
    Model.find_or_create_by(brand_type: 18, name: "RAM")
    Model.find_or_create_by(brand_type: 18, name: "STEALTH")
    Model.find_or_create_by(brand_type: 61, name: "M 100")
    Model.find_or_create_by(brand_type: 61, name: "PLUTUS")
    Model.find_or_create_by(brand_type: 61, name: "START")
    Model.find_or_create_by(brand_type: 61, name: "ULC")
    Model.find_or_create_by(brand_type: 63, name: "ENGESA")
    Model.find_or_create_by(brand_type: 64, name: "CAMPER")
    Model.find_or_create_by(brand_type: 64, name: "MASTER")
    Model.find_or_create_by(brand_type: 10, name: "348")
    Model.find_or_create_by(brand_type: 10, name: "355")
    Model.find_or_create_by(brand_type: 10, name: "360")
    Model.find_or_create_by(brand_type: 10, name: "456")
    Model.find_or_create_by(brand_type: 10, name: "550")
    Model.find_or_create_by(brand_type: 10, name: "M")
    Model.find_or_create_by(brand_type: 10, name: "612")
    Model.find_or_create_by(brand_type: 10, name: "CALIFORNIA")
    Model.find_or_create_by(brand_type: 10, name: "F430")
    Model.find_or_create_by(brand_type: 10, name: "F599")
    Model.find_or_create_by(brand_type: 3, name: "147")
    Model.find_or_create_by(brand_type: 3, name: "500")
    Model.find_or_create_by(brand_type: 3, name: "BRAVA")
    Model.find_or_create_by(brand_type: 3, name: "BRAVO")
    Model.find_or_create_by(brand_type: 3, name: "COUPE")
    Model.find_or_create_by(brand_type: 3, name: "DOBLO")
    Model.find_or_create_by(brand_type: 3, name: "DUCATO CARGO")
    Model.find_or_create_by(brand_type: 3, name: "DUNA")
    Model.find_or_create_by(brand_type: 3, name: "ELBA")
    Model.find_or_create_by(brand_type: 3, name: "FIORINO")
    Model.find_or_create_by(brand_type: 3, name: "FREEMONT")
    Model.find_or_create_by(brand_type: 3, name: "GRAND SIENA")
    Model.find_or_create_by(brand_type: 3, name: "IDEA")
    Model.find_or_create_by(brand_type: 3, name: "LINEA")
    Model.find_or_create_by(brand_type: 3, name: "MAREA")
    Model.find_or_create_by(brand_type: 3, name: "OGGI")
    Model.find_or_create_by(brand_type: 3, name: "PALIO")
    Model.find_or_create_by(brand_type: 3, name: "PANORAMA")
    Model.find_or_create_by(brand_type: 3, name: "PREMIO")
    Model.find_or_create_by(brand_type: 3, name: "PUNTO")
    Model.find_or_create_by(brand_type: 3, name: "SIENA")
    Model.find_or_create_by(brand_type: 3, name: "STILO")
    Model.find_or_create_by(brand_type: 3, name: "STRADA")
    Model.find_or_create_by(brand_type: 3, name: "TEMPRA")
    Model.find_or_create_by(brand_type: 3, name: "TIPO")
    Model.find_or_create_by(brand_type: 3, name: "UNO")
    Model.find_or_create_by(brand_type: 13, name: "AEROSTAR")
    Model.find_or_create_by(brand_type: 13, name: "ASPIRE")
    Model.find_or_create_by(brand_type: 13, name: "BELINA")
    Model.find_or_create_by(brand_type: 13, name: "CLUB WAGON")
    Model.find_or_create_by(brand_type: 13, name: "CONTOUR")
    Model.find_or_create_by(brand_type: 13, name: "CORCEL II")
    Model.find_or_create_by(brand_type: 13, name: "COURIER")
    Model.find_or_create_by(brand_type: 13, name: "CROWN VICTORIA")
    Model.find_or_create_by(brand_type: 13, name: "DEL REY")
    Model.find_or_create_by(brand_type: 13, name: "ECOSPORT")
    Model.find_or_create_by(brand_type: 13, name: "EDGE")
    Model.find_or_create_by(brand_type: 13, name: "ESCORT")
    Model.find_or_create_by(brand_type: 13, name: "EXPEDITION")
    Model.find_or_create_by(brand_type: 13, name: "EXPLORER")
    Model.find_or_create_by(brand_type: 13, name: "F 100")
    Model.find_or_create_by(brand_type: 13, name: "F 1000")
    Model.find_or_create_by(brand_type: 13, name: "F 150")
    Model.find_or_create_by(brand_type: 13, name: "F 250")
    Model.find_or_create_by(brand_type: 13, name: "FIESTA")
    Model.find_or_create_by(brand_type: 13, name: "FOCUS")
    Model.find_or_create_by(brand_type: 13, name: "FURGLAINE")
    Model.find_or_create_by(brand_type: 13, name: "FUSION")
    Model.find_or_create_by(brand_type: 13, name: "IBIZA")
    Model.find_or_create_by(brand_type: 13, name: "KA")
    Model.find_or_create_by(brand_type: 13, name: "MONDEO")
    Model.find_or_create_by(brand_type: 13, name: "MUSTANG")
    Model.find_or_create_by(brand_type: 13, name: "PAMPA")
    Model.find_or_create_by(brand_type: 13, name: "PROBE")
    Model.find_or_create_by(brand_type: 13, name: "RANGER")
    Model.find_or_create_by(brand_type: 13, name: "VERSAILLES ROYALE")
    Model.find_or_create_by(brand_type: 13, name: "TAURUS")
    Model.find_or_create_by(brand_type: 13, name: "THUNDERBIRD")
    Model.find_or_create_by(brand_type: 13, name: "TRANSIT")
    Model.find_or_create_by(brand_type: 13, name: "VERONA")
    Model.find_or_create_by(brand_type: 13, name: "VERSAILLES")
    Model.find_or_create_by(brand_type: 13, name: "WINDSTAR")
    Model.find_or_create_by(brand_type: 1, name: "A 10")
    Model.find_or_create_by(brand_type: 1, name: "A 20")
    Model.find_or_create_by(brand_type: 1, name: "AGILE")
    Model.find_or_create_by(brand_type: 1, name: "ASTRA")
    Model.find_or_create_by(brand_type: 1, name: "BLAZER")
    Model.find_or_create_by(brand_type: 1, name: "BONANZA")
    Model.find_or_create_by(brand_type: 1, name: "C 10")
    Model.find_or_create_by(brand_type: 1, name: "C 20")
    Model.find_or_create_by(brand_type: 1, name: "CALIBRA")
    Model.find_or_create_by(brand_type: 1, name: "CAMARO")
    Model.find_or_create_by(brand_type: 1, name: "CAPRICE")
    Model.find_or_create_by(brand_type: 1, name: "CAPTIVA")
    Model.find_or_create_by(brand_type: 1, name: "CARAVAN")
    Model.find_or_create_by(brand_type: 1, name: "CAVALIER")
    Model.find_or_create_by(brand_type: 1, name: "CELTA")
    Model.find_or_create_by(brand_type: 1, name: "CHEVY")
    Model.find_or_create_by(brand_type: 1, name: "CHEYNNE")
    Model.find_or_create_by(brand_type: 1, name: "COBALT")
    Model.find_or_create_by(brand_type: 1, name: "CORSA")
    Model.find_or_create_by(brand_type: 1, name: "CORVETTE")
    Model.find_or_create_by(brand_type: 1, name: "CRUZE")
    Model.find_or_create_by(brand_type: 1, name: "D 10")
    Model.find_or_create_by(brand_type: 1, name: "D 20")
    Model.find_or_create_by(brand_type: 1, name: "IPANEMA")
    Model.find_or_create_by(brand_type: 1, name: "KADETT")
    Model.find_or_create_by(brand_type: 1, name: "LUMINA")
    Model.find_or_create_by(brand_type: 1, name: "MALIBU")
    Model.find_or_create_by(brand_type: 1, name: "MERIVA")
    Model.find_or_create_by(brand_type: 1, name: "MONTANA")
    Model.find_or_create_by(brand_type: 1, name: "OMEGA")
    Model.find_or_create_by(brand_type: 1, name: "OPALA")
    Model.find_or_create_by(brand_type: 1, name: "PRISMA")
    Model.find_or_create_by(brand_type: 1, name: "S10")
    Model.find_or_create_by(brand_type: 1, name: "SILVERADO")
    Model.find_or_create_by(brand_type: 1, name: "SONIC")
    Model.find_or_create_by(brand_type: 1, name: "SONOMA")
    Model.find_or_create_by(brand_type: 1, name: "SPACEVAN")
    Model.find_or_create_by(brand_type: 1, name: "SS10")
    Model.find_or_create_by(brand_type: 1, name: "SUBURBAN")
    Model.find_or_create_by(brand_type: 1, name: "SYCLONE")
    Model.find_or_create_by(brand_type: 1, name: "TIGRA")
    Model.find_or_create_by(brand_type: 1, name: "TRACKER")
    Model.find_or_create_by(brand_type: 1, name: "TRAFIC")
    Model.find_or_create_by(brand_type: 1, name: "VECTRA")
    Model.find_or_create_by(brand_type: 1, name: "VERANEIO")
    Model.find_or_create_by(brand_type: 1, name: "ZAFIRA")
    Model.find_or_create_by(brand_type: 75, name: "HOVER")
    Model.find_or_create_by(brand_type: 17, name: "BR 800")
    Model.find_or_create_by(brand_type: 17, name: "CARAJAS")
    Model.find_or_create_by(brand_type: 17, name: "TOCANTINS")
    Model.find_or_create_by(brand_type: 17, name: "XAVANTE")
    Model.find_or_create_by(brand_type: 17, name: "VIP")
    Model.find_or_create_by(brand_type: 76, name: "TOWNER")
    Model.find_or_create_by(brand_type: 7, name: "ACCORD")
    Model.find_or_create_by(brand_type: 7, name: "CITY")
    Model.find_or_create_by(brand_type: 7, name: "CIVIC")
    Model.find_or_create_by(brand_type: 7, name: "CR V")
    Model.find_or_create_by(brand_type: 7, name: "FIT")
    Model.find_or_create_by(brand_type: 7, name: "ODYSSEY")
    Model.find_or_create_by(brand_type: 7, name: "PASSPORT")
    Model.find_or_create_by(brand_type: 7, name: "PRELUDE")
    Model.find_or_create_by(brand_type: 14, name: "ACCENT")
    Model.find_or_create_by(brand_type: 14, name: "ATOS")
    Model.find_or_create_by(brand_type: 14, name: "AZERA")
    Model.find_or_create_by(brand_type: 14, name: "COUPE")
    Model.find_or_create_by(brand_type: 14, name: "ELANTRA")
    Model.find_or_create_by(brand_type: 14, name: "EXCEL")
    Model.find_or_create_by(brand_type: 14, name: "GALLOPER")
    Model.find_or_create_by(brand_type: 14, name: "GENESIS")
    Model.find_or_create_by(brand_type: 14, name: "H1")
    Model.find_or_create_by(brand_type: 14, name: "H100")
    Model.find_or_create_by(brand_type: 14, name: "I30")
    Model.find_or_create_by(brand_type: 14, name: "IX35")
    Model.find_or_create_by(brand_type: 14, name: "MATRIX")
    Model.find_or_create_by(brand_type: 14, name: "PORTER")
    Model.find_or_create_by(brand_type: 14, name: "SANTA FE")
    Model.find_or_create_by(brand_type: 14, name: "SCOUPE")
    Model.find_or_create_by(brand_type: 14, name: "SONATA")
    Model.find_or_create_by(brand_type: 14, name: "TERRACAN")
    Model.find_or_create_by(brand_type: 14, name: "TRAJET")
    Model.find_or_create_by(brand_type: 14, name: "TUCSON")
    Model.find_or_create_by(brand_type: 14, name: "VELOSTER")
    Model.find_or_create_by(brand_type: 14, name: "VERACRUZ")
    Model.find_or_create_by(brand_type: 84, name: "AMIGO")
    Model.find_or_create_by(brand_type: 84, name: "HOMBRE")
    Model.find_or_create_by(brand_type: 84, name: "RODEO")
    Model.find_or_create_by(brand_type: 15, name: "J3")
    Model.find_or_create_by(brand_type: 15, name: "J5")
    Model.find_or_create_by(brand_type: 15, name: "J6")
    Model.find_or_create_by(brand_type: 86, name: "DAIMLER")
    Model.find_or_create_by(brand_type: 86, name: "S TYPE")
    Model.find_or_create_by(brand_type: 86, name: "X TYPE")
    Model.find_or_create_by(brand_type: 86, name: "MODELOS XJ")
    Model.find_or_create_by(brand_type: 86, name: "MODELOS XK")
    Model.find_or_create_by(brand_type: 87, name: "CHEROKEE")
    Model.find_or_create_by(brand_type: 87, name: "COMMANDER")
    Model.find_or_create_by(brand_type: 87, name: "COMPASS")
    Model.find_or_create_by(brand_type: 87, name: "GRAND CHEROKEE")
    Model.find_or_create_by(brand_type: 87, name: "WRANGLER")
    Model.find_or_create_by(brand_type: 88, name: "TOPIC VAN")
    Model.find_or_create_by(brand_type: 89, name: "JIPE MONTEZ")
    Model.find_or_create_by(brand_type: 89, name: "PICAPE MONTEZ")
    Model.find_or_create_by(brand_type: 16, name: "BESTA")
    Model.find_or_create_by(brand_type: 16, name: "BONGO")
    Model.find_or_create_by(brand_type: 16, name: "CADENZA")
    Model.find_or_create_by(brand_type: 16, name: "CARENS")
    Model.find_or_create_by(brand_type: 16, name: "CARNIVAL")
    Model.find_or_create_by(brand_type: 16, name: "CERATO")
    Model.find_or_create_by(brand_type: 16, name: "CERES")
    Model.find_or_create_by(brand_type: 16, name: "CLARUS")
    Model.find_or_create_by(brand_type: 16, name: "MAGENTIS")
    Model.find_or_create_by(brand_type: 16, name: "MOHAVE")
    Model.find_or_create_by(brand_type: 16, name: "OPIRUS")
    Model.find_or_create_by(brand_type: 16, name: "OPTIMA")
    Model.find_or_create_by(brand_type: 16, name: "PICANTO")
    Model.find_or_create_by(brand_type: 16, name: "SEPHIA")
    Model.find_or_create_by(brand_type: 16, name: "SHUMA")
    Model.find_or_create_by(brand_type: 16, name: "SORENTO")
    Model.find_or_create_by(brand_type: 16, name: "SOUL")
    Model.find_or_create_by(brand_type: 16, name: "SPORTAGE")
    Model.find_or_create_by(brand_type: 94, name: "LAIKA")
    Model.find_or_create_by(brand_type: 94, name: "NIVA")
    Model.find_or_create_by(brand_type: 94, name: "SAMARA")
    Model.find_or_create_by(brand_type: 12, name: "GALLARDO")
    Model.find_or_create_by(brand_type: 12, name: "MURCIELAGO")
    Model.find_or_create_by(brand_type: 96, name: "DEFENDER")
    Model.find_or_create_by(brand_type: 96, name: "DISCOVERY")
    Model.find_or_create_by(brand_type: 96, name: "FREELANDER")
    Model.find_or_create_by(brand_type: 96, name: "NEW RANGE")
    Model.find_or_create_by(brand_type: 96, name: "RANGE ROVER")
    Model.find_or_create_by(brand_type: 97, name: "ES")
    Model.find_or_create_by(brand_type: 97, name: "GS")
    Model.find_or_create_by(brand_type: 97, name: "IS 300")
    Model.find_or_create_by(brand_type: 97, name: "LS")
    Model.find_or_create_by(brand_type: 97, name: "RX")
    Model.find_or_create_by(brand_type: 97, name: "SC")
    Model.find_or_create_by(brand_type: 98, name: "320")
    Model.find_or_create_by(brand_type: 98, name: "620")
    Model.find_or_create_by(brand_type: 100, name: "H1")
    Model.find_or_create_by(brand_type: 101, name: "ELAN")
    Model.find_or_create_by(brand_type: 101, name: "ESPRIT")
    Model.find_or_create_by(brand_type: 102, name: "SCORPIO")
    Model.find_or_create_by(brand_type: 104, name: "222")
    Model.find_or_create_by(brand_type: 104, name: "228")
    Model.find_or_create_by(brand_type: 104, name: "3200")
    Model.find_or_create_by(brand_type: 104, name: "430")
    Model.find_or_create_by(brand_type: 104, name: "COUPE")
    Model.find_or_create_by(brand_type: 104, name: "GHIBLI")
    Model.find_or_create_by(brand_type: 104, name: "GRANCABRIO")
    Model.find_or_create_by(brand_type: 104, name: "GRANSPORT")
    Model.find_or_create_by(brand_type: 104, name: "GRANTURISMO")
    Model.find_or_create_by(brand_type: 104, name: "QUATTROPORTE")
    Model.find_or_create_by(brand_type: 104, name: "SHAMAL")
    Model.find_or_create_by(brand_type: 104, name: "SPIDER")
    Model.find_or_create_by(brand_type: 106, name: "PICK UP")
    Model.find_or_create_by(brand_type: 108, name: "323")
    Model.find_or_create_by(brand_type: 108, name: "626")
    Model.find_or_create_by(brand_type: 108, name: "929")
    Model.find_or_create_by(brand_type: 108, name: "B 2500")
    Model.find_or_create_by(brand_type: 108, name: "B2200")
    Model.find_or_create_by(brand_type: 108, name: "MILLENIA")
    Model.find_or_create_by(brand_type: 108, name: "MPV")
    Model.find_or_create_by(brand_type: 108, name: "MX 3")
    Model.find_or_create_by(brand_type: 108, name: "MX 5")
    Model.find_or_create_by(brand_type: 108, name: "NAVAJO")
    Model.find_or_create_by(brand_type: 108, name: "PROTEGE")
    Model.find_or_create_by(brand_type: 108, name: "RX")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE A")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE B")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE R")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE GLK")
    Model.find_or_create_by(brand_type: 4, name: "SPRINTER")
    Model.find_or_create_by(brand_type: 110, name: "MYSTIQUE")
    Model.find_or_create_by(brand_type: 110, name: "SABLE")
    Model.find_or_create_by(brand_type: 112, name: "550")
    Model.find_or_create_by(brand_type: 112, name: "MG6")
    Model.find_or_create_by(brand_type: 113, name: "COOPER")
    Model.find_or_create_by(brand_type: 113, name: "ONE")
    Model.find_or_create_by(brand_type: 111, name: "3000")
    Model.find_or_create_by(brand_type: 111, name: "AIRTREK")
    Model.find_or_create_by(brand_type: 111, name: "ASX")
    Model.find_or_create_by(brand_type: 111, name: "COLT")
    Model.find_or_create_by(brand_type: 111, name: "DIAMANT")
    Model.find_or_create_by(brand_type: 111, name: "ECLIPSE")
    Model.find_or_create_by(brand_type: 111, name: "EXPO")
    Model.find_or_create_by(brand_type: 111, name: "GALANT")
    Model.find_or_create_by(brand_type: 111, name: "GRANDIS")
    Model.find_or_create_by(brand_type: 111, name: "L200")
    Model.find_or_create_by(brand_type: 111, name: "L300")
    Model.find_or_create_by(brand_type: 111, name: "LANCER")
    Model.find_or_create_by(brand_type: 111, name: "MIRAGE")
    Model.find_or_create_by(brand_type: 111, name: "MONTERO")
    Model.find_or_create_by(brand_type: 111, name: "OUTLANDER")
    Model.find_or_create_by(brand_type: 111, name: "PAJERO")
    Model.find_or_create_by(brand_type: 111, name: "SPACE WAGON")
    Model.find_or_create_by(brand_type: 114, name: "BG TRUCK")
    Model.find_or_create_by(brand_type: 43, name: "350Z")
    Model.find_or_create_by(brand_type: 43, name: "ALTIMA")
    Model.find_or_create_by(brand_type: 43, name: "AX")
    Model.find_or_create_by(brand_type: 43, name: "D 21")
    Model.find_or_create_by(brand_type: 43, name: "FRONTIER")
    Model.find_or_create_by(brand_type: 43, name: "KING CAB")
    Model.find_or_create_by(brand_type: 43, name: "LIVINA")
    Model.find_or_create_by(brand_type: 43, name: "MARCH")
    Model.find_or_create_by(brand_type: 43, name: "MAXIMA")
    Model.find_or_create_by(brand_type: 43, name: "MURANO")
    Model.find_or_create_by(brand_type: 43, name: "NX")
    Model.find_or_create_by(brand_type: 43, name: "PATHFINDER")
    Model.find_or_create_by(brand_type: 43, name: "PRIMERA")
    Model.find_or_create_by(brand_type: 43, name: "QUEST")
    Model.find_or_create_by(brand_type: 43, name: "SENTRA")
    Model.find_or_create_by(brand_type: 43, name: "STANZA")
    Model.find_or_create_by(brand_type: 43, name: "180SX")
    Model.find_or_create_by(brand_type: 43, name: "TERRANO")
    Model.find_or_create_by(brand_type: 43, name: "TIIDA")
    Model.find_or_create_by(brand_type: 43, name: "VERSA")
    Model.find_or_create_by(brand_type: 43, name: "X TRAIL")
    Model.find_or_create_by(brand_type: 43, name: "XTERRA")
    Model.find_or_create_by(brand_type: 43, name: "ZX")
    Model.find_or_create_by(brand_type: 22, name: "106")
    Model.find_or_create_by(brand_type: 22, name: "205")
    Model.find_or_create_by(brand_type: 22, name: "206")
    Model.find_or_create_by(brand_type: 22, name: "207")
    Model.find_or_create_by(brand_type: 22, name: "3008")
    Model.find_or_create_by(brand_type: 22, name: "306")
    Model.find_or_create_by(brand_type: 22, name: "307")
    Model.find_or_create_by(brand_type: 22, name: "308")
    Model.find_or_create_by(brand_type: 22, name: "405")
    Model.find_or_create_by(brand_type: 22, name: "406")
    Model.find_or_create_by(brand_type: 22, name: "407")
    Model.find_or_create_by(brand_type: 22, name: "408")
    Model.find_or_create_by(brand_type: 22, name: "504")
    Model.find_or_create_by(brand_type: 22, name: "505")
    Model.find_or_create_by(brand_type: 22, name: "508")
    Model.find_or_create_by(brand_type: 22, name: "605")
    Model.find_or_create_by(brand_type: 22, name: "607")
    Model.find_or_create_by(brand_type: 22, name: "806")
    Model.find_or_create_by(brand_type: 22, name: "807")
    Model.find_or_create_by(brand_type: 22, name: "BOXER")
    Model.find_or_create_by(brand_type: 22, name: "HOGGAR")
    Model.find_or_create_by(brand_type: 22, name: "PARTNER")
    Model.find_or_create_by(brand_type: 22, name: "RCZ")
    Model.find_or_create_by(brand_type: 123, name: "GRAN VOYAGER")
    Model.find_or_create_by(brand_type: 123, name: "SUNDANCE")
    Model.find_or_create_by(brand_type: 69, name: "TRANS AM")
    Model.find_or_create_by(brand_type: 69, name: "TRANS SPORT")
    Model.find_or_create_by(brand_type: 70, name: "911")
    Model.find_or_create_by(brand_type: 70, name: "BOXSTER")
    Model.find_or_create_by(brand_type: 70, name: "CAYENNE")
    Model.find_or_create_by(brand_type: 70, name: "CAYMAN")
    Model.find_or_create_by(brand_type: 70, name: "PANAMERA")
    Model.find_or_create_by(brand_type: 24, name: "21 SEDAN")
    Model.find_or_create_by(brand_type: 24, name: "CLIO")
    Model.find_or_create_by(brand_type: 24, name: "DUSTER")
    Model.find_or_create_by(brand_type: 24, name: "EXPRESS")
    Model.find_or_create_by(brand_type: 24, name: "FLUENCE")
    Model.find_or_create_by(brand_type: 24, name: "KANGOO")
    Model.find_or_create_by(brand_type: 24, name: "LAGUNA")
    Model.find_or_create_by(brand_type: 24, name: "LOGAN")
    Model.find_or_create_by(brand_type: 24, name: "MASTER")
    Model.find_or_create_by(brand_type: 24, name: "MEGANE")
    Model.find_or_create_by(brand_type: 24, name: "SAFRANE")
    Model.find_or_create_by(brand_type: 24, name: "SANDERO")
    Model.find_or_create_by(brand_type: 24, name: "SCENIC")
    Model.find_or_create_by(brand_type: 24, name: "SYMBOL")
    Model.find_or_create_by(brand_type: 24, name: "TRAFIC")
    Model.find_or_create_by(brand_type: 24, name: "TWINGO")
    Model.find_or_create_by(brand_type: 137, name: "9000")
    Model.find_or_create_by(brand_type: 162, name: "SL 2")
    Model.find_or_create_by(brand_type: 130, name: "CORDOBA")
    Model.find_or_create_by(brand_type: 130, name: "IBIZA")
    Model.find_or_create_by(brand_type: 130, name: "INCA")
    Model.find_or_create_by(brand_type: 142, name: "FORTWO")
    Model.find_or_create_by(brand_type: 21, name: "ACTYON SPORTS")
    Model.find_or_create_by(brand_type: 21, name: "CHAIRMAN")
    Model.find_or_create_by(brand_type: 21, name: "ISTANA")
    Model.find_or_create_by(brand_type: 21, name: "KORANDO")
    Model.find_or_create_by(brand_type: 21, name: "KYRON")
    Model.find_or_create_by(brand_type: 21, name: "MUSSO")
    Model.find_or_create_by(brand_type: 21, name: "REXTON")
    Model.find_or_create_by(brand_type: 8, name: "FORESTER")
    Model.find_or_create_by(brand_type: 8, name: "IMPREZA")
    Model.find_or_create_by(brand_type: 8, name: "LEGACY")
    Model.find_or_create_by(brand_type: 8, name: "OUTBACK")
    Model.find_or_create_by(brand_type: 8, name: "SVX")
    Model.find_or_create_by(brand_type: 8, name: "TRIBECA")
    Model.find_or_create_by(brand_type: 8, name: "VIVIO")
    Model.find_or_create_by(brand_type: 59, name: "BALENO")
    Model.find_or_create_by(brand_type: 59, name: "GRAND VITARA")
    Model.find_or_create_by(brand_type: 59, name: "IGNIS")
    Model.find_or_create_by(brand_type: 59, name: "JIMNY")
    Model.find_or_create_by(brand_type: 59, name: "SUPER CARRY")
    Model.find_or_create_by(brand_type: 59, name: "SWIFT")
    Model.find_or_create_by(brand_type: 59, name: "SX4")
    Model.find_or_create_by(brand_type: 59, name: "VITARA")
    Model.find_or_create_by(brand_type: 59, name: "WAGON R")
    Model.find_or_create_by(brand_type: 146, name: "STARK")
    Model.find_or_create_by(brand_type: 23, name: "AVALON")
    Model.find_or_create_by(brand_type: 23, name: "BANDEIRANTE")
    Model.find_or_create_by(brand_type: 23, name: "CAMRY")
    Model.find_or_create_by(brand_type: 23, name: "CELICA")
    Model.find_or_create_by(brand_type: 23, name: "COROLLA")
    Model.find_or_create_by(brand_type: 23, name: "CORONA")
    Model.find_or_create_by(brand_type: 23, name: "HILUX")
    Model.find_or_create_by(brand_type: 23, name: "LAND CRUISER")
    Model.find_or_create_by(brand_type: 23, name: "MR 2")
    Model.find_or_create_by(brand_type: 23, name: "PASEO")
    Model.find_or_create_by(brand_type: 23, name: "PREVIA")
    Model.find_or_create_by(brand_type: 23, name: "RAV4")
    Model.find_or_create_by(brand_type: 23, name: "SUPRA")
    Model.find_or_create_by(brand_type: 149, name: "PANTANAL")
    Model.find_or_create_by(brand_type: 149, name: "T 4")
    Model.find_or_create_by(brand_type: 53, name: "400 SERIES")
    Model.find_or_create_by(brand_type: 53, name: "850")
    Model.find_or_create_by(brand_type: 53, name: "900 SERIES")
    Model.find_or_create_by(brand_type: 2, name: "AMAROK")
    Model.find_or_create_by(brand_type: 2, name: "APOLLO")
    Model.find_or_create_by(brand_type: 2, name: "BORA")
    Model.find_or_create_by(brand_type: 2, name: "CARAVELLE")
    Model.find_or_create_by(brand_type: 2, name: "CORRADO")
    Model.find_or_create_by(brand_type: 2, name: "EOS")
    Model.find_or_create_by(brand_type: 2, name: "EUROVAN")
    Model.find_or_create_by(brand_type: 2, name: "FOX")
    Model.find_or_create_by(brand_type: 2, name: "FUSCA")
    Model.find_or_create_by(brand_type: 2, name: "GOL")
    Model.find_or_create_by(brand_type: 2, name: "GOLF")
    Model.find_or_create_by(brand_type: 2, name: "JETTA")
    Model.find_or_create_by(brand_type: 2, name: "KOMBI")
    Model.find_or_create_by(brand_type: 2, name: "LOGUS")
    Model.find_or_create_by(brand_type: 2, name: "PARATI")
    Model.find_or_create_by(brand_type: 2, name: "PASSAT")
    Model.find_or_create_by(brand_type: 2, name: "POINTER")
    Model.find_or_create_by(brand_type: 2, name: "POLO")
    Model.find_or_create_by(brand_type: 2, name: "SANTANA")
    Model.find_or_create_by(brand_type: 2, name: "SAVEIRO")
    Model.find_or_create_by(brand_type: 2, name: "SPACEFOX")
    Model.find_or_create_by(brand_type: 2, name: "TIGUAN")
    Model.find_or_create_by(brand_type: 2, name: "TOUAREG")
    Model.find_or_create_by(brand_type: 2, name: "VOYAGE")
    Model.find_or_create_by(brand_type: 25, name: "ZDX")
    Model.find_or_create_by(brand_type: 3, name: "140")
    Model.find_or_create_by(brand_type: 2, name: "BRASILIA")
    Model.find_or_create_by(brand_type: 13, name: "BRASILVAN")
    Model.find_or_create_by(brand_type: 13, name: "CORCEL")
    Model.find_or_create_by(brand_type: 3, name: "PALIO WEEKEND")
    Model.find_or_create_by(brand_type: 13, name: "FOCUS SEDAN")
    Model.find_or_create_by(brand_type: 13, name: "FIESTA SEDAN")
    Model.find_or_create_by(brand_type: 13, name: "FIESTA TRAIL")
    Model.find_or_create_by(brand_type: 22, name: "207 SW")
    Model.find_or_create_by(brand_type: 13, name: "ESCORT SW")
    Model.find_or_create_by(brand_type: 22, name: "307 SEDAN")
    Model.find_or_create_by(brand_type: 22, name: "307 SW")
    Model.find_or_create_by(brand_type: 5, name: "C4 PALLAS")
    Model.find_or_create_by(brand_type: 5, name: "C4 PICASSO")
    Model.find_or_create_by(brand_type: 5, name: "C4 VTR")
    Model.find_or_create_by(brand_type: 24, name: "CLIO SEDAN")
    Model.find_or_create_by(brand_type: 23, name: "COROLLA FIELDER")
    Model.find_or_create_by(brand_type: 23, name: "HILUX SW4")
    Model.find_or_create_by(brand_type: 24, name: "MEGANE GRAND TOUR")
    Model.find_or_create_by(brand_type: 24, name: "SANDERO STEPWAY")
    Model.find_or_create_by(brand_type: 5, name: "XSARA PICASSO")
    Model.find_or_create_by(brand_type: 131, name: "COLHEITADEIRA")
    Model.find_or_create_by(brand_type: 158, name: "PICKUP F75")
    Model.find_or_create_by(brand_type: 17, name: "X12")
    Model.find_or_create_by(brand_type: 1, name: "BEL AIR")
    Model.find_or_create_by(brand_type: 36, name: "RX")
    Model.find_or_create_by(brand_type: 1, name: "C 14")
    Model.find_or_create_by(brand_type: 155, name: "SRX4")
    Model.find_or_create_by(brand_type: 1, name: "C 15")
    Model.find_or_create_by(brand_type: 1, name: "BRASIL")
    Model.find_or_create_by(brand_type: 18, name: "POLARA")
    Model.find_or_create_by(brand_type: 3, name: "600")
    Model.find_or_create_by(brand_type: 13, name: "F 01")
    Model.find_or_create_by(brand_type: 13, name: "FALCON")
    Model.find_or_create_by(brand_type: 13, name: "GALAXIE")
    Model.find_or_create_by(brand_type: 13, name: "MAVERICK")
    Model.find_or_create_by(brand_type: 13, name: "MODELO A")
    Model.find_or_create_by(brand_type: 13, name: "NEW FIESTA")
    Model.find_or_create_by(brand_type: 82, name: "LINHA FX")
    Model.find_or_create_by(brand_type: 124, name: "GTS")
    Model.find_or_create_by(brand_type: 80, name: "H3")
    Model.find_or_create_by(brand_type: 14, name: "PRIME")
    Model.find_or_create_by(brand_type: 14, name: "TIBURON")
    Model.find_or_create_by(brand_type: 87, name: "JEEP")
    Model.find_or_create_by(brand_type: 87, name: "CJ5")
    Model.find_or_create_by(brand_type: 239, name: "TC")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE CLC")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE CLS")
    Model.find_or_create_by(brand_type: 110, name: "MONTEREY")
    Model.find_or_create_by(brand_type: 114, name: "TOPSPORT")
    Model.find_or_create_by(brand_type: 114, name: "TARGA")
    Model.find_or_create_by(brand_type: 114, name: "X8")
    Model.find_or_create_by(brand_type: 43, name: "370Z")
    Model.find_or_create_by(brand_type: 124, name: "GTB")
    Model.find_or_create_by(brand_type: 124, name: "GTC")
    Model.find_or_create_by(brand_type: 124, name: "GTE")
    Model.find_or_create_by(brand_type: 115, name: "AUSTIN")
    Model.find_or_create_by(brand_type: 24, name: "7TL")
    Model.find_or_create_by(brand_type: 24, name: "19")
    Model.find_or_create_by(brand_type: 175, name: "CONVERSÍVEL")
    Model.find_or_create_by(brand_type: 17, name: "SUPERMINI")
    Model.find_or_create_by(brand_type: 2, name: "TL")
    Model.find_or_create_by(brand_type: 3, name: "TOPOLINO")
    Model.find_or_create_by(brand_type: 23, name: "SR5")
    Model.find_or_create_by(brand_type: 23, name: "VITZ")
    Model.find_or_create_by(brand_type: 2, name: "VARIANT")
    Model.find_or_create_by(brand_type: 57, name: "CANDANGO")
    Model.find_or_create_by(brand_type: 2, name: "SP2")
    Model.find_or_create_by(brand_type: 258, name: "RECORB")
    Model.find_or_create_by(brand_type: 2, name: "POLAUTO")
    Model.find_or_create_by(brand_type: 24, name: "GORDINI")
    Model.find_or_create_by(brand_type: 265, name: "MINX")
    Model.find_or_create_by(brand_type: 23, name: "ETIOS")
    Model.find_or_create_by(brand_type: 1, name: "ONIX")
    Model.find_or_create_by(brand_type: 14, name: "HB20")
    Model.find_or_create_by(brand_type: 36, name: "330")
    Model.find_or_create_by(brand_type: 36, name: "520")
    Model.find_or_create_by(brand_type: 36, name: "730")
    Model.find_or_create_by(brand_type: 36, name: "M1")
    Model.find_or_create_by(brand_type: 36, name: "SERIE Z")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE SLK")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE C")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE E")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE CL")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE CLK")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE S")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE SL")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE SLS")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE G")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE GL")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE M")
    Model.find_or_create_by(brand_type: 288, name: "1500")
    Model.find_or_create_by(brand_type: 14, name: "EQUUS")
    Model.find_or_create_by(brand_type: 12, name: "350 GT")
    Model.find_or_create_by(brand_type: 12, name: "400 GT")
    Model.find_or_create_by(brand_type: 12, name: "MIURA")
    Model.find_or_create_by(brand_type: 12, name: "ISLERO")
    Model.find_or_create_by(brand_type: 12, name: "ESPADA")
    Model.find_or_create_by(brand_type: 12, name: "COUNTACH")
    Model.find_or_create_by(brand_type: 12, name: "DIABLO")
    Model.find_or_create_by(brand_type: 12, name: "ZAGATO")
    Model.find_or_create_by(brand_type: 12, name: "ALAR")
    Model.find_or_create_by(brand_type: 12, name: "LM002")
    Model.find_or_create_by(brand_type: 12, name: "REVENTON")
    Model.find_or_create_by(brand_type: 12, name: "ANKONIAN")
    Model.find_or_create_by(brand_type: 12, name: "AVENTADOR")
    Model.find_or_create_by(brand_type: 12, name: "SESTO ELEMENTO")
    Model.find_or_create_by(brand_type: 15, name: "J3 TURIN")
    Model.find_or_create_by(brand_type: 15, name: "J2")
    Model.find_or_create_by(brand_type: 24, name: "SANDERO GT")
    Model.find_or_create_by(brand_type: 1, name: "SPIN")
    Model.find_or_create_by(brand_type: 1, name: "TRAILBLAZER")
    Model.find_or_create_by(brand_type: 5, name: "C3 PICASSO")
    Model.find_or_create_by(brand_type: 5, name: "GRAND C4 PICASSO")
    Model.find_or_create_by(brand_type: 5, name: "JUMPER MINIBUS")
    Model.find_or_create_by(brand_type: 5, name: "JUMPER VETRATO")
    Model.find_or_create_by(brand_type: 22, name: "207 SEDAN")
    Model.find_or_create_by(brand_type: 22, name: "207 QUIKSILVER")
    Model.find_or_create_by(brand_type: 22, name: "207 ESCAPADE")
    Model.find_or_create_by(brand_type: 22, name: "308 CC")
    Model.find_or_create_by(brand_type: 22, name: "BOXER PASSAGEIRO")
    Model.find_or_create_by(brand_type: 13, name: "NEW FIESTA SEDAN")
    Model.find_or_create_by(brand_type: 13, name: "TRANSIT PASSAGEIRO")
    Model.find_or_create_by(brand_type: 13, name: "TRANSIT CHASSI")
    Model.find_or_create_by(brand_type: 32, name: "A4 AVANT")
    Model.find_or_create_by(brand_type: 32, name: "S4 AVANT")
    Model.find_or_create_by(brand_type: 32, name: "A5 SPORTBACK")
    Model.find_or_create_by(brand_type: 32, name: "A5 CABRIOLET")
    Model.find_or_create_by(brand_type: 32, name: "S5 COUPE")
    Model.find_or_create_by(brand_type: 32, name: "S5 SPORTBACK")
    Model.find_or_create_by(brand_type: 32, name: "S5 CABRIOLET")
    Model.find_or_create_by(brand_type: 32, name: "A6 AVANT")
    Model.find_or_create_by(brand_type: 32, name: "A6 ALLROAD")
    Model.find_or_create_by(brand_type: 32, name: "S6 AVANT")
    Model.find_or_create_by(brand_type: 32, name: "S7")
    Model.find_or_create_by(brand_type: 32, name: "TT ROADSTER")
    Model.find_or_create_by(brand_type: 32, name: "TT RS")
    Model.find_or_create_by(brand_type: 32, name: "TT RS ROADSTER")
    Model.find_or_create_by(brand_type: 32, name: "TTS ROADSTER")
    Model.find_or_create_by(brand_type: 32, name: "R8 SPYDER")
    Model.find_or_create_by(brand_type: 32, name: "R8 GT")
    Model.find_or_create_by(brand_type: 32, name: "R8 GT SPYDER")
    Model.find_or_create_by(brand_type: 10, name: "F12")
    Model.find_or_create_by(brand_type: 10, name: "458 SPIDER")
    Model.find_or_create_by(brand_type: 10, name: "458 ITALIA")
    Model.find_or_create_by(brand_type: 10, name: "FF")
    Model.find_or_create_by(brand_type: 10, name: "599")
    Model.find_or_create_by(brand_type: 10, name: "SA")
    Model.find_or_create_by(brand_type: 10, name: "CHALLENGE")
    Model.find_or_create_by(brand_type: 10, name: "SUPERAMERICA")
    Model.find_or_create_by(brand_type: 10, name: "F430 SPIDER")
    Model.find_or_create_by(brand_type: 10, name: "430")
    Model.find_or_create_by(brand_type: 10, name: "612 SESSANTA")
    Model.find_or_create_by(brand_type: 10, name: "599 GTB")
    Model.find_or_create_by(brand_type: 10, name: "SCUDERIA SPIDER")
    Model.find_or_create_by(brand_type: 10, name: "512")
    Model.find_or_create_by(brand_type: 10, name: "456 GT")
    Model.find_or_create_by(brand_type: 10, name: "348 GTS")
    Model.find_or_create_by(brand_type: 10, name: "348 SPIDER")
    Model.find_or_create_by(brand_type: 10, name: "F355")
    Model.find_or_create_by(brand_type: 10, name: "F355 SPIDER")
    Model.find_or_create_by(brand_type: 10, name: "F50")
    Model.find_or_create_by(brand_type: 10, name: "355 SPIDER")
    Model.find_or_create_by(brand_type: 10, name: "360 MODENA")
    Model.find_or_create_by(brand_type: 111, name: "PAJERO FULL")
    Model.find_or_create_by(brand_type: 111, name: "PAJERO DAKAR")
    Model.find_or_create_by(brand_type: 111, name: "PAJERO TR4")
    Model.find_or_create_by(brand_type: 111, name: "LANCER SPORTBACK")
    Model.find_or_create_by(brand_type: 111, name: "LANCER EVOLUTION")
    Model.find_or_create_by(brand_type: 111, name: "L200 TRITON SAVANA")
    Model.find_or_create_by(brand_type: 111, name: "L200 TRITON")
    Model.find_or_create_by(brand_type: 43, name: "LIVINA X GEAR")
    Model.find_or_create_by(brand_type: 43, name: "GRAND LIVINA")
    Model.find_or_create_by(brand_type: 21, name: "NEW ACTYON SPORTS")
    Model.find_or_create_by(brand_type: 23, name: "PRIUS")
    Model.find_or_create_by(brand_type: 114, name: "SPORT")
    Model.find_or_create_by(brand_type: 114, name: "MTS")
    Model.find_or_create_by(brand_type: 114, name: "SPIDER")
    Model.find_or_create_by(brand_type: 114, name: "KABRIO")
    Model.find_or_create_by(brand_type: 114, name: "SAGA")
    Model.find_or_create_by(brand_type: 114, name: "SAGA II")
    Model.find_or_create_by(brand_type: 114, name: "787")
    Model.find_or_create_by(brand_type: 114, name: "X11")
    Model.find_or_create_by(brand_type: 295, name: "GAIOLA")
    Model.find_or_create_by(brand_type: 18, name: "NITRO")
    Model.find_or_create_by(brand_type: 18, name: "CHALLENGER")
    Model.find_or_create_by(brand_type: 18, name: "DART")
    Model.find_or_create_by(brand_type: 18, name: "LE BARON")
    Model.find_or_create_by(brand_type: 18, name: "CORDOBA")
    Model.find_or_create_by(brand_type: 18, name: "CHARGER")
    Model.find_or_create_by(brand_type: 19, name: "WINDSOR")
    Model.find_or_create_by(brand_type: 19, name: "CROSSFIRE")
    Model.find_or_create_by(brand_type: 19, name: "CORDOBA")
    Model.find_or_create_by(brand_type: 155, name: "ESCALADE")
    Model.find_or_create_by(brand_type: 41, name: "RIVIERA")
    Model.find_or_create_by(brand_type: 41, name: "COUPE")
    Model.find_or_create_by(brand_type: 41, name: "CENTURY")
    Model.find_or_create_by(brand_type: 41, name: "APOLLO")
    Model.find_or_create_by(brand_type: 41, name: "CENTURION")
    Model.find_or_create_by(brand_type: 41, name: "EIGHT")
    Model.find_or_create_by(brand_type: 41, name: "ELECTRA")
    Model.find_or_create_by(brand_type: 41, name: "ESTATE WAGON")
    Model.find_or_create_by(brand_type: 41, name: "GRAN SPORT")
    Model.find_or_create_by(brand_type: 41, name: "GSX")
    Model.find_or_create_by(brand_type: 41, name: "INVICTA")
    Model.find_or_create_by(brand_type: 41, name: "LESABRE")
    Model.find_or_create_by(brand_type: 41, name: "LIMITED")
    Model.find_or_create_by(brand_type: 41, name: "PARK AVENUE")
    Model.find_or_create_by(brand_type: 41, name: "RAINIER")
    Model.find_or_create_by(brand_type: 41, name: "REATTA")
    Model.find_or_create_by(brand_type: 41, name: "REGAL")
    Model.find_or_create_by(brand_type: 41, name: "RENDEZVOUS")
    Model.find_or_create_by(brand_type: 41, name: "ROADMASTER")
    Model.find_or_create_by(brand_type: 41, name: "ROYAUM")
    Model.find_or_create_by(brand_type: 41, name: "SKYHAWK")
    Model.find_or_create_by(brand_type: 41, name: "SKYLARK")
    Model.find_or_create_by(brand_type: 41, name: "SOMERSET")
    Model.find_or_create_by(brand_type: 41, name: "SPECIAL")
    Model.find_or_create_by(brand_type: 41, name: "SPORT WAGON")
    Model.find_or_create_by(brand_type: 41, name: "SUPER")
    Model.find_or_create_by(brand_type: 41, name: "TERRAZA")
    Model.find_or_create_by(brand_type: 41, name: "WILDCAT")
    Model.find_or_create_by(brand_type: 41, name: "LACROSSE")
    Model.find_or_create_by(brand_type: 41, name: "ENCLAVE")
    Model.find_or_create_by(brand_type: 41, name: "GL8")
    Model.find_or_create_by(brand_type: 41, name: "HRV")
    Model.find_or_create_by(brand_type: 41, name: "LUCERNE")
    Model.find_or_create_by(brand_type: 13, name: "SIERRA")
    Model.find_or_create_by(brand_type: 51, name: "BROUGHAM")
    Model.find_or_create_by(brand_type: 51, name: "CHAIRMAN")
    Model.find_or_create_by(brand_type: 51, name: "DAMAS")
    Model.find_or_create_by(brand_type: 51, name: "GENTRA")
    Model.find_or_create_by(brand_type: 51, name: "MAEPSY")
    Model.find_or_create_by(brand_type: 51, name: "ISTANA")
    Model.find_or_create_by(brand_type: 51, name: "KALOS")
    Model.find_or_create_by(brand_type: 51, name: "KORANDO")
    Model.find_or_create_by(brand_type: 51, name: "LACETTI")
    Model.find_or_create_by(brand_type: 51, name: "LEMANS")
    Model.find_or_create_by(brand_type: 51, name: "MATIZ")
    Model.find_or_create_by(brand_type: 51, name: "MUSSO")
    Model.find_or_create_by(brand_type: 51, name: "NEXIA")
    Model.find_or_create_by(brand_type: 51, name: "REZZO")
    Model.find_or_create_by(brand_type: 51, name: "ROYALE PRINCE")
    Model.find_or_create_by(brand_type: 51, name: "ROYALE SALON")
    Model.find_or_create_by(brand_type: 51, name: "STATESMAN")
    Model.find_or_create_by(brand_type: 51, name: "TOSCA")
    Model.find_or_create_by(brand_type: 51, name: "WINSTORM")
    Model.find_or_create_by(brand_type: 158, name: "RURAL")
    Model.find_or_create_by(brand_type: 18, name: "D100")
    Model.find_or_create_by(brand_type: 4, name: "170")
    Model.find_or_create_by(brand_type: 18, name: "CUSTOM ROYAL")
    Model.find_or_create_by(brand_type: 1, name: "CLUB COUPE")
    Model.find_or_create_by(brand_type: 18, name: "MAGNUM")
    Model.find_or_create_by(brand_type: 1, name: "GMC 100")
    Model.find_or_create_by(brand_type: 69, name: "SOLSTICE")
    Model.find_or_create_by(brand_type: 158, name: "ITAMARATY")
    Model.find_or_create_by(brand_type: 86, name: "MARK V")
    Model.find_or_create_by(brand_type: 124, name: "GT")
    Model.find_or_create_by(brand_type: 145, name: "CHAMPION")
    Model.find_or_create_by(brand_type: 3, name: "BALILLA")
    Model.find_or_create_by(brand_type: 158, name: "INTERLAGOS")
    Model.find_or_create_by(brand_type: 17, name: "X15")
    Model.find_or_create_by(brand_type: 13, name: "F 85")
    Model.find_or_create_by(brand_type: 70, name: "SPEEDSTER 356")
    Model.find_or_create_by(brand_type: 88, name: "TOPIC FURGAO")
    Model.find_or_create_by(brand_type: 88, name: "TOPIC ESCOLAR")
    Model.find_or_create_by(brand_type: 4, name: "300D")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE TE")
    Model.find_or_create_by(brand_type: 23, name: "T 100")
    Model.find_or_create_by(brand_type: 24, name: "MEGANE SEDAN")
    Model.find_or_create_by(brand_type: 32, name: "A4 CABRIOLET")
    Model.find_or_create_by(brand_type: 82, name: "LINHA G")
    Model.find_or_create_by(brand_type: 82, name: "LINHA G COUPE")
    Model.find_or_create_by(brand_type: 82, name: "LINHA G CONVERSIVEL")
    Model.find_or_create_by(brand_type: 82, name: "LINHA M")
    Model.find_or_create_by(brand_type: 82, name: "LINHA EX")
    Model.find_or_create_by(brand_type: 82, name: "LINHA JX")
    Model.find_or_create_by(brand_type: 82, name: "LINHA QX")
    Model.find_or_create_by(brand_type: 86, name: "MODELOS XF")
    Model.find_or_create_by(brand_type: 86, name: "F TYPE")
    Model.find_or_create_by(brand_type: 86, name: "MARK VII")
    Model.find_or_create_by(brand_type: 86, name: "MARK VIII")
    Model.find_or_create_by(brand_type: 86, name: "MARK IX")
    Model.find_or_create_by(brand_type: 86, name: "MARK X")
    Model.find_or_create_by(brand_type: 86, name: "E TYPE")
    Model.find_or_create_by(brand_type: 86, name: "C TYPE")
    Model.find_or_create_by(brand_type: 86, name: "D TYPE")
    Model.find_or_create_by(brand_type: 86, name: "MARK I")
    Model.find_or_create_by(brand_type: 86, name: "MARK II")
    Model.find_or_create_by(brand_type: 124, name: "GT4R")
    Model.find_or_create_by(brand_type: 124, name: "SPYDER")
    Model.find_or_create_by(brand_type: 124, name: "GTI")
    Model.find_or_create_by(brand_type: 124, name: "AM1")
    Model.find_or_create_by(brand_type: 124, name: "AM2")
    Model.find_or_create_by(brand_type: 124, name: "AM3")
    Model.find_or_create_by(brand_type: 124, name: "AM4")
    Model.find_or_create_by(brand_type: 124, name: "AMV")
    Model.find_or_create_by(brand_type: 7, name: "ACTY")
    Model.find_or_create_by(brand_type: 7, name: "AIRWAVE")
    Model.find_or_create_by(brand_type: 7, name: "ASCOT")
    Model.find_or_create_by(brand_type: 7, name: "BALLADE")
    Model.find_or_create_by(brand_type: 7, name: "BEAT")
    Model.find_or_create_by(brand_type: 7, name: "CR X")
    Model.find_or_create_by(brand_type: 7, name: "CONCERTO")
    Model.find_or_create_by(brand_type: 7, name: "CR Z")
    Model.find_or_create_by(brand_type: 7, name: "DOMANI")
    Model.find_or_create_by(brand_type: 7, name: "EDIX")
    Model.find_or_create_by(brand_type: 7, name: "ELEMENT")
    Model.find_or_create_by(brand_type: 7, name: "EV PLUS")
    Model.find_or_create_by(brand_type: 7, name: "FCX")
    Model.find_or_create_by(brand_type: 7, name: "FR V")
    Model.find_or_create_by(brand_type: 7, name: "HR V")
    Model.find_or_create_by(brand_type: 7, name: "HSC")
    Model.find_or_create_by(brand_type: 7, name: "INSIGHT")
    Model.find_or_create_by(brand_type: 25, name: "TL")
    Model.find_or_create_by(brand_type: 7, name: "LIFE DUNK")
    Model.find_or_create_by(brand_type: 7, name: "LOGO")
    Model.find_or_create_by(brand_type: 7, name: "MOBILIO")
    Model.find_or_create_by(brand_type: 25, name: "MDX")
    Model.find_or_create_by(brand_type: 7, name: "ORTHIA")
    Model.find_or_create_by(brand_type: 7, name: "PARTNER VAN")
    Model.find_or_create_by(brand_type: 7, name: "PILOT")
    Model.find_or_create_by(brand_type: 7, name: "RIDGELINE")
    Model.find_or_create_by(brand_type: 7, name: "S2000")
    Model.find_or_create_by(brand_type: 7, name: "S600")
    Model.find_or_create_by(brand_type: 7, name: "S500")
    Model.find_or_create_by(brand_type: 7, name: "S800")
    Model.find_or_create_by(brand_type: 7, name: "STEPWGN")
    Model.find_or_create_by(brand_type: 7, name: "STREAM")
    Model.find_or_create_by(brand_type: 7, name: "THATS")
    Model.find_or_create_by(brand_type: 7, name: "VAMOZ")
    Model.find_or_create_by(brand_type: 7, name: "Z")
    Model.find_or_create_by(brand_type: 7, name: "ZEST")
    Model.find_or_create_by(brand_type: 59, name: "AERIO")
    Model.find_or_create_by(brand_type: 59, name: "ALTO")
    Model.find_or_create_by(brand_type: 59, name: "APV")
    Model.find_or_create_by(brand_type: 59, name: "KEI")
    Model.find_or_create_by(brand_type: 59, name: "LAPIN")
    Model.find_or_create_by(brand_type: 59, name: "MR WAGON")
    Model.find_or_create_by(brand_type: 59, name: "XL 7")
    Model.find_or_create_by(brand_type: 59, name: "VERONA")
    Model.find_or_create_by(brand_type: 158, name: "JEEP CJ")
    Model.find_or_create_by(brand_type: 22, name: "306 CABRIOLET")
    Model.find_or_create_by(brand_type: 57, name: "BELCAR")
    Model.find_or_create_by(brand_type: 90, name: "M715")
    Model.find_or_create_by(brand_type: 22, name: "407 SW")
    Model.find_or_create_by(brand_type: 22, name: "307 CC")
    Model.find_or_create_by(brand_type: 1, name: "STYLELINE")
    Model.find_or_create_by(brand_type: 13, name: "ANGLIA")
    Model.find_or_create_by(brand_type: 26, name: "GT2")
    Model.find_or_create_by(brand_type: 1, name: "YUKON")
    Model.find_or_create_by(brand_type: 54, name: "SPORTSMAN")
    Model.find_or_create_by(brand_type: 24, name: "21 NEVADA")
    Model.find_or_create_by(brand_type: 11, name: "VEYRON")
    Model.find_or_create_by(brand_type: 10, name: "ENZO")
    Model.find_or_create_by(brand_type: 22, name: "306 SW")
    Model.find_or_create_by(brand_type: 28, name: "TI 80")
    Model.find_or_create_by(brand_type: 70, name: "SPYDER 550")
    Model.find_or_create_by(brand_type: 10, name: "380 GTB")
    Model.find_or_create_by(brand_type: 149, name: "T 5")
    Model.find_or_create_by(brand_type: 18, name: "KINGSWAY")
    Model.find_or_create_by(brand_type: 1, name: "SSR")
    Model.find_or_create_by(brand_type: 1, name: "IMPALA")
    Model.find_or_create_by(brand_type: 22, name: "208")
    Model.find_or_create_by(brand_type: 1, name: "GRAND BLAZER")
    Model.find_or_create_by(brand_type: 53, name: "100 SERIES")
    Model.find_or_create_by(brand_type: 53, name: "200 SERIES")
    Model.find_or_create_by(brand_type: 53, name: "300 SERIES")
    Model.find_or_create_by(brand_type: 53, name: "66")
    Model.find_or_create_by(brand_type: 53, name: "700 SERIES")
    Model.find_or_create_by(brand_type: 53, name: "AMAZON")
    Model.find_or_create_by(brand_type: 53, name: "C303")
    Model.find_or_create_by(brand_type: 53, name: "DUETT")
    Model.find_or_create_by(brand_type: 53, name: "L3314")
    Model.find_or_create_by(brand_type: 53, name: "OV 4")
    Model.find_or_create_by(brand_type: 53, name: "P1800")
    Model.find_or_create_by(brand_type: 53, name: "SUGGA")
    Model.find_or_create_by(brand_type: 13, name: "TT")
    Model.find_or_create_by(brand_type: 5, name: "ONCE")
    Model.find_or_create_by(brand_type: 13, name: "DE LUXE")
    Model.find_or_create_by(brand_type: 13, name: "CUSTOM")
    Model.find_or_create_by(brand_type: 13, name: "T BUCKET")
    Model.find_or_create_by(brand_type: 17, name: "G15")
    Model.find_or_create_by(brand_type: 111, name: "PAJERO FULL 3D")
    Model.find_or_create_by(brand_type: 111, name: "PAJERO SPORT")
    Model.find_or_create_by(brand_type: 36, name: "120 CABRIO")
    Model.find_or_create_by(brand_type: 36, name: "320 TOURING")
    Model.find_or_create_by(brand_type: 36, name: "330 CABRIO")
    Model.find_or_create_by(brand_type: 36, name: "SERIE 5 TOURING")
    Model.find_or_create_by(brand_type: 36, name: "SERIE 6 CABRIO")
    Model.find_or_create_by(brand_type: 36, name: "SERIE M CONVERSIVEL")
    Model.find_or_create_by(brand_type: 36, name: "M5 TOURING")
    Model.find_or_create_by(brand_type: 36, name: "SERIE Z ROADSTER")
    Model.find_or_create_by(brand_type: 13, name: "KA SPORT")
    Model.find_or_create_by(brand_type: 2, name: "CC")
    Model.find_or_create_by(brand_type: 16, name: "CERATO KOUP")
    Model.find_or_create_by(brand_type: 1, name: "ASTRO")
    Model.find_or_create_by(brand_type: 23, name: "COROLLA XRS")
    Model.find_or_create_by(brand_type: 23, name: "ETIOS SEDAN")
    Model.find_or_create_by(brand_type: 13, name: "FREESTYLE")
    Model.find_or_create_by(brand_type: 110, name: "COUGAR")
    Model.find_or_create_by(brand_type: 102, name: "XUV 500")
    Model.find_or_create_by(brand_type: 102, name: "XYLO")
    Model.find_or_create_by(brand_type: 102, name: "BOLERO")
    Model.find_or_create_by(brand_type: 102, name: "THAR")
    Model.find_or_create_by(brand_type: 102, name: "AXE")
    Model.find_or_create_by(brand_type: 102, name: "LEGEND")
    Model.find_or_create_by(brand_type: 87, name: "CJ3")
    Model.find_or_create_by(brand_type: 102, name: "ARMADA")
    Model.find_or_create_by(brand_type: 102, name: "CHASSI")
    Model.find_or_create_by(brand_type: 102, name: "SCORPIO PICK UP")
    Model.find_or_create_by(brand_type: 6, name: "STAR TRUCK")
    Model.find_or_create_by(brand_type: 6, name: "STAR")
    Model.find_or_create_by(brand_type: 6, name: "STAR VAN CARGO")
    Model.find_or_create_by(brand_type: 6, name: "STAR VAN PASSAGEIROS")
    Model.find_or_create_by(brand_type: 141, name: "ALVORADA")
    Model.find_or_create_by(brand_type: 141, name: "CHAMBORD")
    Model.find_or_create_by(brand_type: 141, name: "PROFISSIONAL")
    Model.find_or_create_by(brand_type: 141, name: "VEDETTE")
    Model.find_or_create_by(brand_type: 141, name: "ARONDE")
    Model.find_or_create_by(brand_type: 141, name: "1200S")
    Model.find_or_create_by(brand_type: 141, name: "1000")
    Model.find_or_create_by(brand_type: 14, name: "HB20X")
    Model.find_or_create_by(brand_type: 14, name: "HB20S")
    Model.find_or_create_by(brand_type: 1, name: "MONZA")
    Model.find_or_create_by(brand_type: 1, name: "CHEVETTE")
    Model.find_or_create_by(brand_type: 98, name: "X60")
    Model.find_or_create_by(brand_type: 1, name: "TRAX")
    Model.find_or_create_by(brand_type: 36, name: "118")
    Model.find_or_create_by(brand_type: 36, name: "120")
    Model.find_or_create_by(brand_type: 36, name: "130")
    Model.find_or_create_by(brand_type: 36, name: "BAVARIA")
    Model.find_or_create_by(brand_type: 36, name: "C 2800")
    Model.find_or_create_by(brand_type: 36, name: "318")
    Model.find_or_create_by(brand_type: 36, name: "320")
    Model.find_or_create_by(brand_type: 36, name: "318 CABRIO")
    Model.find_or_create_by(brand_type: 36, name: "325 CABRIO")
    Model.find_or_create_by(brand_type: 36, name: "530")
    Model.find_or_create_by(brand_type: 36, name: "540")
    Model.find_or_create_by(brand_type: 36, name: "550")
    Model.find_or_create_by(brand_type: 36, name: "740")
    Model.find_or_create_by(brand_type: 36, name: "750")
    Model.find_or_create_by(brand_type: 36, name: "760")
    Model.find_or_create_by(brand_type: 341, name: "MATRIX 4X4")
    Model.find_or_create_by(brand_type: 132, name: "A7")
    Model.find_or_create_by(brand_type: 132, name: "A9")
    Model.find_or_create_by(brand_type: 132, name: "A9 CARGO")
    Model.find_or_create_by(brand_type: 132, name: "T20")
    Model.find_or_create_by(brand_type: 132, name: "T20 BAU")
    Model.find_or_create_by(brand_type: 132, name: "T22")
    Model.find_or_create_by(brand_type: 64, name: "SUPER 90 COUPE")
    Model.find_or_create_by(brand_type: 17, name: "X20")
    Model.find_or_create_by(brand_type: 17, name: "ITAIPU")
    Model.find_or_create_by(brand_type: 17, name: "G800")
    Model.find_or_create_by(brand_type: 17, name: "XEF")
    Model.find_or_create_by(brand_type: 17, name: "MOTOMACHINE")
    Model.find_or_create_by(brand_type: 17, name: "BUGATO")
    Model.find_or_create_by(brand_type: 17, name: "QT")
    Model.find_or_create_by(brand_type: 57, name: "CAICARA")
    Model.find_or_create_by(brand_type: 57, name: "CARCARA")
    Model.find_or_create_by(brand_type: 57, name: "FISSORE")
    Model.find_or_create_by(brand_type: 57, name: "MALZONI")
    Model.find_or_create_by(brand_type: 57, name: "VEMAGUET")
    Model.find_or_create_by(brand_type: 5, name: "C4 LOUNGE")
    Model.find_or_create_by(brand_type: 108, name: "CX 7")
    Model.find_or_create_by(brand_type: 147, name: "TR")
    Model.find_or_create_by(brand_type: 147, name: "LUCENA")
    Model.find_or_create_by(brand_type: 147, name: "SEVETSE")
    Model.find_or_create_by(brand_type: 147, name: "RAGGE")
    Model.find_or_create_by(brand_type: 53, name: "C70")
    Model.find_or_create_by(brand_type: 53, name: "C30")
    Model.find_or_create_by(brand_type: 53, name: "544")
    Model.find_or_create_by(brand_type: 53, name: "S40")
    Model.find_or_create_by(brand_type: 53, name: "S60")
    Model.find_or_create_by(brand_type: 53, name: "S70")
    Model.find_or_create_by(brand_type: 53, name: "S80")
    Model.find_or_create_by(brand_type: 53, name: "V40")
    Model.find_or_create_by(brand_type: 53, name: "V50")
    Model.find_or_create_by(brand_type: 53, name: "V60")
    Model.find_or_create_by(brand_type: 53, name: "V70")
    Model.find_or_create_by(brand_type: 53, name: "S90")
    Model.find_or_create_by(brand_type: 53, name: "XC60")
    Model.find_or_create_by(brand_type: 53, name: "XC70")
    Model.find_or_create_by(brand_type: 53, name: "XC90")
    Model.find_or_create_by(brand_type: 53, name: "P1900")
    Model.find_or_create_by(brand_type: 53, name: "PV36")
    Model.find_or_create_by(brand_type: 53, name: "PV444")
    Model.find_or_create_by(brand_type: 53, name: "PV544")
    Model.find_or_create_by(brand_type: 53, name: "PV51")
    Model.find_or_create_by(brand_type: 53, name: "PV654")
    Model.find_or_create_by(brand_type: 53, name: "C50")
    Model.find_or_create_by(brand_type: 4, name: "190")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE CLA")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE V")
    Model.find_or_create_by(brand_type: 4, name: "VANEO")
    Model.find_or_create_by(brand_type: 4, name: "CITAN")
    Model.find_or_create_by(brand_type: 4, name: "VARIO")
    Model.find_or_create_by(brand_type: 4, name: "CLASSE S CLASSICO")
    Model.find_or_create_by(brand_type: 15, name: "J3S")
    Model.find_or_create_by(brand_type: 345, name: "PICK UP")
    Model.find_or_create_by(brand_type: 345, name: "VAN")
    Model.find_or_create_by(brand_type: 5, name: "C3 SOLARIS")
    Model.find_or_create_by(brand_type: 5, name: "C3 XTR")
    Model.find_or_create_by(brand_type: 5, name: "C4 SOLARIS")
    Model.find_or_create_by(brand_type: 5, name: "C5 BREAK TOURER")
    Model.find_or_create_by(brand_type: 5, name: "XSARA BREAK")
    Model.find_or_create_by(brand_type: 5, name: "XSARA VTS")
    Model.find_or_create_by(brand_type: 5, name: "XANTIA BREAK")
    Model.find_or_create_by(brand_type: 5, name: "XM BREAK")
    Model.find_or_create_by(brand_type: 5, name: "C15")
    Model.find_or_create_by(brand_type: 5, name: "NEMO")
    Model.find_or_create_by(brand_type: 5, name: "VISA")
    Model.find_or_create_by(brand_type: 5, name: "C1")
    Model.find_or_create_by(brand_type: 5, name: "C2")
    Model.find_or_create_by(brand_type: 5, name: "C3 PLURIEL")
    Model.find_or_create_by(brand_type: 5, name: "DS4")
    Model.find_or_create_by(brand_type: 5, name: "DS5")
    Model.find_or_create_by(brand_type: 5, name: "JUMPY")
    Model.find_or_create_by(brand_type: 5, name: "C CROSSER")
    Model.find_or_create_by(brand_type: 5, name: "C35")
    Model.find_or_create_by(brand_type: 5, name: "C25")
    Model.find_or_create_by(brand_type: 5, name: "CX")
    Model.find_or_create_by(brand_type: 5, name: "CX BREAK")
    Model.find_or_create_by(brand_type: 5, name: "AXEL")
    Model.find_or_create_by(brand_type: 5, name: "DYANE")
    Model.find_or_create_by(brand_type: 5, name: "GS GSA")
    Model.find_or_create_by(brand_type: 5, name: "GS GSA BREAK")
    Model.find_or_create_by(brand_type: 5, name: "MEHARI")
    Model.find_or_create_by(brand_type: 5, name: "SAXO")
    Model.find_or_create_by(brand_type: 5, name: "SM")
    Model.find_or_create_by(brand_type: 5, name: "ELYSEE")
    Model.find_or_create_by(brand_type: 24, name: "MASTER MINIBUS")
    Model.find_or_create_by(brand_type: 47, name: "CELER")
    Model.find_or_create_by(brand_type: 47, name: "CELER SEDAN")
    Model.find_or_create_by(brand_type: 47, name: "CIELO SEDAN")
    Model.find_or_create_by(brand_type: 32, name: "A1 SPORTBACK")
    Model.find_or_create_by(brand_type: 32, name: "A1 QUATTRO")
    Model.find_or_create_by(brand_type: 32, name: "A3 SPORTBACK")
    Model.find_or_create_by(brand_type: 32, name: "RS4 AVANT")
    Model.find_or_create_by(brand_type: 32, name: "A8L W12")
    Model.find_or_create_by(brand_type: 32, name: "R8 V10")
    Model.find_or_create_by(brand_type: 13, name: "RANGER CD")
    Model.find_or_create_by(brand_type: 15, name: "T140")
    Model.find_or_create_by(brand_type: 36, name: "X1")
    Model.find_or_create_by(brand_type: 36, name: "X3")
    Model.find_or_create_by(brand_type: 36, name: "X5")
    Model.find_or_create_by(brand_type: 36, name: "X6")
    Model.find_or_create_by(brand_type: 36, name: "840")
    Model.find_or_create_by(brand_type: 36, name: "850")
    Model.find_or_create_by(brand_type: 36, name: "645")
    Model.find_or_create_by(brand_type: 36, name: "650")
    Model.find_or_create_by(brand_type: 7, name: "FIT TWIST")
    Model.find_or_create_by(brand_type: 346, name: "MP4")
    Model.find_or_create_by(brand_type: 346, name: "F1")
    Model.find_or_create_by(brand_type: 13, name: "MONDEO SW")
    Model.find_or_create_by(brand_type: 13, name: "ESCORT SEDAN")
    Model.find_or_create_by(brand_type: 13, name: "ESCORT CONVERSIVEL")
    Model.find_or_create_by(brand_type: 108, name: "MX 6")
    Model.find_or_create_by(brand_type: 1, name: "CORISCO")
    Model.find_or_create_by(brand_type: 1, name: "CHEVELLE")
    Model.find_or_create_by(brand_type: 13, name: "EXCURSION")
    Model.find_or_create_by(brand_type: 2, name: "TOURAN")
    Model.find_or_create_by(brand_type: 13, name: "F 10000")
    Model.find_or_create_by(brand_type: 22, name: "HOGGAR ESCAPADE")
    Model.find_or_create_by(brand_type: 13, name: "PHAETON")
    Model.find_or_create_by(brand_type: 2, name: "TRANSPORTER")
    Model.find_or_create_by(brand_type: 16, name: "GRAND BESTA")
    Model.find_or_create_by(brand_type: 43, name: "200SX")
    Model.find_or_create_by(brand_type: 43, name: "240SX")
    Model.find_or_create_by(brand_type: 19, name: "300M")
    Model.find_or_create_by(brand_type: 19, name: "300C TOURING")
    Model.find_or_create_by(brand_type: 13, name: "TORINO")
    Model.find_or_create_by(brand_type: 1, name: "VENTURE")
    Model.find_or_create_by(brand_type: 1, name: "FLEETLINE")
    Model.find_or_create_by(brand_type: 1, name: "FLEETMASTER")
    Model.find_or_create_by(brand_type: 1, name: "DELUXE")
    Model.find_or_create_by(brand_type: 13, name: "ESCORT XR3")
    Model.find_or_create_by(brand_type: 1, name: "MASTER")
    Model.find_or_create_by(brand_type: 120, name: "TORONADO")
    Model.find_or_create_by(brand_type: 120, name: "SIX")
    Model.find_or_create_by(brand_type: 120, name: "EIGHT")
    Model.find_or_create_by(brand_type: 120, name: "DELUXE")
    Model.find_or_create_by(brand_type: 120, name: "SERIES 60")
    Model.find_or_create_by(brand_type: 120, name: "SERIES 70")
    Model.find_or_create_by(brand_type: 120, name: "SERIES 80")
    Model.find_or_create_by(brand_type: 120, name: "SERIES 90")
    Model.find_or_create_by(brand_type: 120, name: "STARFIRE")
    Model.find_or_create_by(brand_type: 120, name: "442")
    Model.find_or_create_by(brand_type: 120, name: "CUTLASS")
    Model.find_or_create_by(brand_type: 120, name: "CUTLASS SUPREME")
    Model.find_or_create_by(brand_type: 120, name: "CUTLASS SALON")
    Model.find_or_create_by(brand_type: 120, name: "CUTLASS CALAIS")
    Model.find_or_create_by(brand_type: 120, name: "CUTLASS CIERA")
    Model.find_or_create_by(brand_type: 120, name: "CUSTOM CRUISER")
    Model.find_or_create_by(brand_type: 120, name: "VISTA CRUISER")
    Model.find_or_create_by(brand_type: 120, name: "F 85")
    Model.find_or_create_by(brand_type: 120, name: "FIRENZA")
    Model.find_or_create_by(brand_type: 120, name: "ACHIEVA")
    Model.find_or_create_by(brand_type: 120, name: "ALERO")
    Model.find_or_create_by(brand_type: 120, name: "AURORA")
    Model.find_or_create_by(brand_type: 120, name: "BRAVADA")
    Model.find_or_create_by(brand_type: 120, name: "INTRIGUE")
    Model.find_or_create_by(brand_type: 120, name: "SILHOUETTE")
    Model.find_or_create_by(brand_type: 123, name: "SUPERBIRD")
    Model.find_or_create_by(brand_type: 123, name: "FURY")
    Model.find_or_create_by(brand_type: 123, name: "SPECIAL")
    Model.find_or_create_by(brand_type: 123, name: "PROWLER")
    Model.find_or_create_by(brand_type: 123, name: "TRAIL DUSTER")
    Model.find_or_create_by(brand_type: 123, name: "VOYAGER")
    Model.find_or_create_by(brand_type: 123, name: "SCAMP")
    Model.find_or_create_by(brand_type: 123, name: "ARROW")
    Model.find_or_create_by(brand_type: 123, name: "PT50")
    Model.find_or_create_by(brand_type: 123, name: "PT57")
    Model.find_or_create_by(brand_type: 123, name: "PT81")
    Model.find_or_create_by(brand_type: 123, name: "PT105")
    Model.find_or_create_by(brand_type: 123, name: "PT125")
    Model.find_or_create_by(brand_type: 123, name: "EXPRESS")
    Model.find_or_create_by(brand_type: 123, name: "VOYAGER EXPRESSO")
    Model.find_or_create_by(brand_type: 123, name: "NEON")
    Model.find_or_create_by(brand_type: 123, name: "LASER")
    Model.find_or_create_by(brand_type: 123, name: "CARAVELLE")
    Model.find_or_create_by(brand_type: 123, name: "STATION WAGON")
    Model.find_or_create_by(brand_type: 123, name: "MODEL Q")
    Model.find_or_create_by(brand_type: 123, name: "MODEL P6")
    Model.find_or_create_by(brand_type: 31, name: "DB9 COUPE")
    Model.find_or_create_by(brand_type: 31, name: "DB9 VOLANTE")
    Model.find_or_create_by(brand_type: 31, name: "VIRAGE COUPE")
    Model.find_or_create_by(brand_type: 31, name: "RAPIDE S")
    Model.find_or_create_by(brand_type: 31, name: "V12 VANTAGE")
    Model.find_or_create_by(brand_type: 31, name: "V8 VANTAGE COUPE")
    Model.find_or_create_by(brand_type: 31, name: "V8 VANTAGE ROADSTER")
    Model.find_or_create_by(brand_type: 31, name: "V8 VANTAGE S COUPE")
    Model.find_or_create_by(brand_type: 31, name: "V8 VANTAGE S ROADSTER")
    Model.find_or_create_by(brand_type: 31, name: "VANQUISH COUPE")
    Model.find_or_create_by(brand_type: 31, name: "VANQUISH VOLANTE")
    Model.find_or_create_by(brand_type: 31, name: "V12 ZAGATO")
    Model.find_or_create_by(brand_type: 31, name: "DB5")
    Model.find_or_create_by(brand_type: 31, name: "DBS")
    Model.find_or_create_by(brand_type: 31, name: "DBS VOLANTE")
    Model.find_or_create_by(brand_type: 31, name: "CYGNET")
    Model.find_or_create_by(brand_type: 31, name: "ONE 77")
    Model.find_or_create_by(brand_type: 31, name: "DBR9")
    Model.find_or_create_by(brand_type: 36, name: "M3")
    Model.find_or_create_by(brand_type: 36, name: "M5")
    Model.find_or_create_by(brand_type: 36, name: "M6")
    Model.find_or_create_by(brand_type: 36, name: "X6 M")
    Model.find_or_create_by(brand_type: 113, name: "CABRIO")
    Model.find_or_create_by(brand_type: 113, name: "COUPE")
    Model.find_or_create_by(brand_type: 113, name: "ROADSTER")
    Model.find_or_create_by(brand_type: 113, name: "COUNTRYMAN")
    Model.find_or_create_by(brand_type: 113, name: "PACEMAN")
    Model.find_or_create_by(brand_type: 113, name: "JOHN COOPER WORKS")
    Model.find_or_create_by(brand_type: 122, name: "ZONDA")
    Model.find_or_create_by(brand_type: 8, name: "NEW XV")
    Model.find_or_create_by(brand_type: 8, name: "IMPREZA WRX HATCH")
    Model.find_or_create_by(brand_type: 8, name: "IMPREZA WRX STI HATCH")
    Model.find_or_create_by(brand_type: 8, name: "IMPREZA WRX STI SEDAN")
    Model.find_or_create_by(brand_type: 8, name: "IMPREZA WRX SEDAN")
    Model.find_or_create_by(brand_type: 23, name: "ETIOS CROSS")
    Model.find_or_create_by(brand_type: 12, name: "HURACAN")
    Model.find_or_create_by(brand_type: 2, name: "UP")
    Model.find_or_create_by(brand_type: 195, name: "EXPLORER")
    Model.find_or_create_by(brand_type: 142, name: "FORTWO CABRIO")
    Model.find_or_create_by(brand_type: 26, name: "GT")
    Model.find_or_create_by(brand_type: 26, name: "GTL")
    Model.find_or_create_by(brand_type: 26, name: "GTM")
    Model.find_or_create_by(brand_type: 26, name: "C2")
    Model.find_or_create_by(brand_type: 26, name: "CRX")
    Model.find_or_create_by(brand_type: 26, name: "AC 2000")
    Model.find_or_create_by(brand_type: 99, name: "AVIATOR")
    Model.find_or_create_by(brand_type: 99, name: "BLACKWOOD")
    Model.find_or_create_by(brand_type: 99, name: "CAPRI")
    Model.find_or_create_by(brand_type: 99, name: "CONTINENTAL")
    Model.find_or_create_by(brand_type: 99, name: "LS")
    Model.find_or_create_by(brand_type: 99, name: "MARK")
    Model.find_or_create_by(brand_type: 99, name: "MARK LT")
    Model.find_or_create_by(brand_type: 99, name: "MKR")
    Model.find_or_create_by(brand_type: 99, name: "MKS")
    Model.find_or_create_by(brand_type: 99, name: "MKX")
    Model.find_or_create_by(brand_type: 99, name: "MKZ")
    Model.find_or_create_by(brand_type: 99, name: "NAVIGATOR")
    Model.find_or_create_by(brand_type: 99, name: "PREMIERE")
    Model.find_or_create_by(brand_type: 99, name: "TOWN CAR")
    Model.find_or_create_by(brand_type: 99, name: "VERSAILLES")
    Model.find_or_create_by(brand_type: 99, name: "ZEPHYR")
    Model.find_or_create_by(brand_type: 1, name: "CLASSIC")
    Model.find_or_create_by(brand_type: 21, name: "ACTYON")
    Model.find_or_create_by(brand_type: 1, name: "MARAJO")
    Model.find_or_create_by(brand_type: 1, name: "SUPREMA")
    Model.find_or_create_by(brand_type: 2, name: "NEW BEETLE")
    Model.find_or_create_by(brand_type: 2, name: "QUANTUM")
    Model.find_or_create_by(brand_type: 2, name: "CROSSFOX")
    Model.find_or_create_by(brand_type: 3, name: "MILLE")
    Model.find_or_create_by(brand_type: 534, name: "GC2")
    Model.find_or_create_by(brand_type: 534, name: "EC7")
    Model.find_or_create_by(brand_type: 98, name: "530")
    Model.find_or_create_by(brand_type: 3, name: "MOBI")
    Model.find_or_create_by(brand_type: 3, name: "TORO")
    Model.find_or_create_by(brand_type: 87, name: "RENEGADE")
    Model.find_or_create_by(brand_type: 24, name: "DUSTER OROCH")
    Model.find_or_create_by(brand_type: 24, name: "SANDERO RS")
    Model.find_or_create_by(brand_type: 14, name: "HB20R")
    Model.find_or_create_by(brand_type: 14, name: "GRAND SANTA FE")
    Model.find_or_create_by(brand_type: 2, name: "GOLF VARIANT")
    Model.find_or_create_by(brand_type: 2, name: "SPACE CROSS")
    Model.find_or_create_by(brand_type: 22, name: "2008")
    Model.find_or_create_by(brand_type: 16, name: "QUORIS")
    Model.find_or_create_by(brand_type: 16, name: "GRAND CARNIVAL")
    Model.find_or_create_by(brand_type: 15, name: "T8")
    Model.find_or_create_by(brand_type: 15, name: "T6")
    Model.find_or_create_by(brand_type: 15, name: "T5")
    Model.find_or_create_by(brand_type: 13, name: "KA SEDAN")
    Model.find_or_create_by(brand_type: 13, name: "FOCUS FASTBACK")
  end
end
